name: wpwatchlist #project name
recipe: wordpress
config:
  php: '7.4' # PHP Version
  composer_version: '2' # set to 1 | 1-latest | 2 | 2-latest https://docs.lando.dev/config/php.html#installing-composer
  via: apache # nginx or apache
  webroot: wp
  database: mysql # mysql or mariadb
  xdebug: debug
  config:
    php: .vscode/php.ini