name: wp-starter #Here comes your project name
recipe: wordpress
config:
  php: '8.1' # PHP version
  composer_version: '2' # Composer version
  via: nginx # apache or nginx
  webroot: wordpress
  xdebug: true # Enable xdebug
  database: mariadb # mysql or mariadb
  config:
    php: config/php.ini
services:
  appserver:
    overrides:
      volumes:
          - ./src/wp-starter:/app/wordpress/wp-content/plugins/wp-starter #Replace with your own plugin.
          #- ./src/wp-starter:/app/wordpress/wp-content/themes/wp-starter #For theme development.
  pma:
      type: phpmyadmin # Creates a phpmyadmin container called "pma".
      hosts:
        - database
  mailhog:
    type: mailhog # Creates mailhog container called "mailhog".
    hogfrom: # Hog from appserver or nginx
      - appserver
tooling:
  setup-wordpress: #creates command: 'lando setup-wordpress'
    service: appserver # where to run the command
    description: Downloads and installs WordPress in 10 seconds
    cmd: # For more commands see wp-cli docs: https://github.com/wp-cli/core-command
      # Download wordpress (US version)
      - wp core download --locale=en_US --path=wordpress
      # Create wp-config.php with defaults. Allow user to install files into folders (NEVER use in production!).
      - wp config create --dbname=wordpress --dbuser=wordpress --dbpass=wordpress --dbhost=database --path=wordpress --extra-php="define('FS_METHOD','direct');"
      # Install wordpress. Change title, admin_user, admin_password and admin_email.
      - wp core install --url=https://wp-starter.lndo.site/ --title="wp-starter" --admin_user=admin --admin_password=admin --admin_email=admin@wp-starter.wherever --path=wordpress
