name: wpwatchlist #project name
recipe: wordpress
config:
  php: '7.4' # PHP Version
  composer_version: '2' # set to 1 | 1-latest | 2 | 2-latest https://docs.lando.dev/config/php.html#installing-composer
  via: apache # apache or nginx
  webroot: wordpress
  database: mysql # mysql or mariadb
  xdebug: debug
  config:
    php: .vscode/php.ini
services:
  pma:
      type: phpmyadmin # Spin up a phpmyadmin container called "pma".
      hosts:
        - database
tooling:
  install-wordpress: #creates command: 'lando install-wordpress'
    service: appserver
    description: Installs WordPress in 5 seconds
    cmd:
      # For more commands see wp-cli docs: https://github.com/wp-cli/core-command
      - mkdir wordpress   #Create folder 'wordpress'
      - wp core download --path=wordpress #Download wordpress to path 'wordpress'
      - wp config create --path=wordpress --dbname=wordpress --dbuser=wordpress --dbpass=wordpress --dbhost=database #Create config with given values. Done!