name: wp-starter #Here comes your project name
recipe: wordpress
config:
  php: '8.1' # PHP version
  composer_version: '2' # Composer version
  via: nginx # apache or nginx
  webroot: wordpress
  database: mariadb # mysql or mariadb
  xdebug: debug #custom xdebug config. More info: https://docs.lando.dev/guides/lando-with-vscode.html#getting-started
  config:
    php: config/php.ini
services:
  appserver:
    overrides:
      volumes:
          - ./src/wp-starter:/app/wordpress/wp-content/plugins/wp-starter #Replace with your own plugin.
          #- ./src/theme-name:/app/wordpress/wp-content/themes/project-name #For theme development.
  pma:
      type: phpmyadmin # Creates a phpmyadmin container called "pma".
      hosts:
        - database
  mailhog:
    type: mailhog # Creates mailhog container called "mailhog".
    hogfrom: # Hog from appserver or nginx
      - appserver
tooling:
  download-wordpress: #creates command: 'lando download-wordpress'
    service: appserver
    description: Downloads WordPress in 10 seconds
    cmd:
      # For more commands see wp-cli docs: https://github.com/wp-cli/core-command
      - wp core download --path=wordpress #Download wordpress to path 'wordpress'
      - wp config create --path=wordpress --dbname=wordpress --dbuser=wordpress --dbpass=wordpress --dbhost=database #Create config with given values. Done!